import GucchiBag from "../assets/images/Gucchibag.png";
import KeyboardRGB from "../assets/images/KeyboardRGB.png";
import LcdMonitor from "../assets/images/LcdMonitor.png";
import SatinJacket from "../assets/images/Quilted-Satin-Jacket.png";
import UsbGameConsole from "../assets/images/USBGameConsole.png";
import consoleRed from "../assets/images/consoleRed.png";
import LaptopLenovo from "../assets/images/lenovoLaptop.png";
import RgbLiquidCooler from "../assets/images/rgbliquidcooler.png";

import { v4 as uuidv4 } from 'uuid';
import DeleteVectorIcon from "../assets/images/DeleteVectorIcon.svg";

export const WishlistUserSelectedItems = [
  {
    id: uuidv4(),
    img: GucchiBag,
    text: "Gucci duffle bag",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: "-35%",
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: RgbLiquidCooler,
    text: "RGB liquid CPU Cooler",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: UsbGameConsole,
    text: "GP11 Shooter USB Gamepad",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: SatinJacket,
    text: "Quilted Satin Jacket",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: GucchiBag,
    text: "Gucci duffle bag",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: "-35%",
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: RgbLiquidCooler,
    text: "RGB liquid CPU Cooler",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: UsbGameConsole,
    text: "GP11 Shooter USB Gamepad",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: SatinJacket,
    text: "Quilted Satin Jacket",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: GucchiBag,
    text: "Gucci duffle bag",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: "-35%",
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: RgbLiquidCooler,
    text: "RGB liquid CPU Cooler",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: UsbGameConsole,
    text: "GP11 Shooter USB Gamepad",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: SatinJacket,
    text: "Quilted Satin Jacket",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: GucchiBag,
    text: "Gucci duffle bag",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: "-35%",
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: RgbLiquidCooler,
    text: "RGB liquid CPU Cooler",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: UsbGameConsole,
    text: "GP11 Shooter USB Gamepad",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: SatinJacket,
    text: "Quilted Satin Jacket",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
];


export const UserByingRealtedProducts = [
  {
    id: uuidv4(),
    img: LaptopLenovo,
    text: "ASUS FHD Gaming Laptop",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
  },
  {
    id: uuidv4(),
    img: LcdMonitor,
    text: "IPS LCD Gaming Monitor",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: "-35%",
    offer: null,
    priceActual: 1160,
    priceOld: null,
  },
  {
    id: uuidv4(),
    img: consoleRed,
    text: "HAVIT HV-G92 Gamepad",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: "New",
    priceActual: 560,
    priceOld: null,
  },
  {
    id: uuidv4(),
    img: KeyboardRGB,
    text: "AK-900 Wired Keyboard",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 200,
    priceOld: null,
  },
]



export const CartList = [
  {
    id: uuidv4(),
    img: GucchiBag,
    text: "Gucci duffle bag",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: "-35%",
    priceActual: 960,
    priceOld: 1160,
    quantity: 2,
    subTotal: 1500,
  },
  {
    id: uuidv4(),
    img: RgbLiquidCooler,
    text: "RGB liquid CPU Cooler",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
    quantity: 2,
    subTotal: 1500,
  },
  {
    id: uuidv4(),
    img: GucchiBag,
    text: "Gucci duffle bag",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: "-35%",
    priceActual: 960,
    priceOld: 1160,
    quantity: 2,
    subTotal: 1500,
  },
  {
    id: uuidv4(),
    img: RgbLiquidCooler,
    text: "RGB liquid CPU Cooler",
    link: "Add To Cart",
    iconDelete: DeleteVectorIcon,
    offer: null,
    priceActual: 960,
    priceOld: 1160,
    quantity: 2,
    subTotal: 1500,
  },
  // {
  //   id: uuidv4(),
  //   img: UsbGameConsole,
  //   text: "GP11 Shooter USB Gamepad",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500,
  // },
  // {
  //   id: uuidv4(),
  //   img: SatinJacket,
  //   text: "Quilted Satin Jacket",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500,
  // },
  // {
  //   id: uuidv4(),
  //   img: GucchiBag,
  //   text: "Gucci duffle bag",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: "-35%",
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500,
  // },
  // {
  //   id: uuidv4(),
  //   img: RgbLiquidCooler,
  //   text: "RGB liquid CPU Cooler",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500,
  // },
  // {
  //   id: uuidv4(),
  //   img: UsbGameConsole,
  //   text: "GP11 Shooter USB Gamepad",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500,
  // },
  // {
  //   id: uuidv4(),
  //   img: SatinJacket,
  //   text: "Quilted Satin Jacket",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500,
  // },
  // {
  //   id: uuidv4(),
  //   img: GucchiBag,
  //   text: "Gucci duffle bag",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: "-35%",
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500,
  //   quantity: 2,
  //   subTotal: 1500,
  // },
  // {
  //   id: uuidv4(),
  //   img: RgbLiquidCooler,
  //   text: "RGB liquid CPU Cooler",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500
  // },
  // {
  //   id: uuidv4(),
  //   img: UsbGameConsole,
  //   text: "GP11 Shooter USB Gamepad",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500
  // },
  // {
  //   id: uuidv4(),
  //   img: SatinJacket,
  //   text: "Quilted Satin Jacket",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500
  // },
  // {
  //   id: uuidv4(),
  //   img: GucchiBag,
  //   text: "Gucci duffle bag",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: "-35%",
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500
  // },
  // {
  //   id: uuidv4(),
  //   img: RgbLiquidCooler,
  //   text: "RGB liquid CPU Cooler",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500
  // },
  // {
  //   id: uuidv4(),
  //   img: UsbGameConsole,
  //   text: "GP11 Shooter USB Gamepad",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500
  // },
  // {
  //   id: uuidv4(),
  //   img: SatinJacket,
  //   text: "Quilted Satin Jacket",
  //   link: "Add To Cart",
  //   iconDelete: DeleteVectorIcon,
  //   offer: null,
  //   priceActual: 960,
  //   priceOld: 1160,
  //   quantity: 2,
  //   subTotal: 1500
  // },
];